#name: Gh-Pages
#
#on:
#  push:
#    branches: [ master ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2 # Only works with v2
#      - uses: subosito/flutter-action@v1
#      - uses: bluefireteam/flutter-gh-pages@v7
#        with:
#          baseHref: /sunufoof/
##yy
##          deploy_key: ${{ secrets.DEPLOY_KEY }} # Clé SSH privée pour accéder au référentiel GitHub
##          publish_branch: gh-pages # Branche sur laquelle les fichiers de build seront déployés
##          publish_dir: build/web # Dossier contenant les fichiers de build générés
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Le nom de la branche sur laquelle vous souhaitez déclencher le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.5 # La version de Flutter à utiliser

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }} # Clé SSH privée pour accéder au référentiel GitHub
          publish_branch: gh-pages # Branche sur laquelle les fichiers de build seront déployés
          publish_dir: build/web # Dossier contenant les fichiers de build générés

